import React from 'react';
import { X, Printer, Download, Share2, ShieldCheck, Building2, Calendar, FileText } from 'lucide-react';
import StatusBadge from '../common/StatusBadge';

export default function ReportViewModal({ report, isOpen, onClose }) {
  if (!isOpen || !report) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
      <div className="bg-white rounded-2xl max-w-2xl w-full p-8 shadow-2xl border border-slate-200 relative max-h-[90vh] overflow-y-auto animate-scaleUp">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 print:hidden"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Printable Formal Header */}
        <div className="border-b-2 border-slate-800 pb-4 mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-blue-900 text-white font-black text-xl px-3 py-1.5 rounded">
                BIS
              </div>
              <div>
                <h2 className="text-xl font-extrabold tracking-tight text-slate-900">BIS Sahayak (मानक सहायक)</h2>
                <p className="text-xs text-slate-500">Intelligent Standards Compliance & Verification Analysis</p>
              </div>
            </div>

            <div className="text-right text-xs">
              <div className="font-mono text-slate-600 font-bold">{report.id}</div>
              <div className="text-slate-400">{report.date}</div>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="space-y-6 text-xs text-slate-700">
          <div className="flex items-start justify-between">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Report Subject</span>
              <h3 className="text-base font-bold text-slate-900 mt-0.5">{report.title}</h3>
              {report.standard_id && (
                <div className="text-blue-700 font-semibold mt-1">Standard: {report.standard_id}</div>
              )}
            </div>
            <StatusBadge status={report.status} />
          </div>

          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <strong className="text-slate-800 block mb-1 text-xs">Executive Summary</strong>
            <p className="text-slate-600 leading-relaxed text-xs">{report.summary}</p>
          </div>

          {/* Details Table */}
          {report.details && (
            <div>
              <strong className="text-slate-800 block mb-2 text-xs">Technical Parameter Details</strong>
              <div className="border border-slate-200 rounded-lg overflow-hidden">
                <table className="w-full text-left text-xs">
                  <tbody className="divide-y divide-slate-100">
                    {Object.entries(report.details).map(([k, v], idx) => (
                      <tr key={idx} className="hover:bg-slate-50">
                        <td className="p-2.5 font-semibold text-slate-700 capitalize bg-slate-50/50 w-1/3">
                          {k.replace(/_/g, ' ')}
                        </td>
                        <td className="p-2.5 font-mono text-slate-800">
                          {typeof v === 'object' ? JSON.stringify(v) : String(v)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Disclaimer */}
          <div className="p-3.5 bg-amber-50 rounded-xl border border-amber-200 text-[11px] text-amber-900 leading-relaxed">
            <strong>Statutory Disclaimer:</strong> This document is generated by the BIS Sahayak AI analysis engine for technical verification and internal quality review. It distinguishes analytical guidance from an official Bureau of Indian Standards (BIS) statutory conformity certificate.
          </div>
        </div>

        {/* Footer Actions */}
        <div className="border-t border-slate-200 mt-8 pt-4 flex justify-between items-center print:hidden">
          <span className="text-[11px] text-slate-400">SIH 2026 • BIS Sahayak Analysis</span>
          <div className="flex space-x-2">
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-lg border border-slate-300 hover:bg-slate-100 text-slate-700 text-xs font-semibold flex items-center space-x-1.5"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={() => alert('Report downloaded as PDF.')}
              className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold flex items-center space-x-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
